controller_names:
  - xarm6_controller
  - xarm6_gripper_controller

xarm6_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

xarm6_gripper_controller:
  # action_ns: gripper_action
  # type: GripperCommand
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - drive_joint