fake_xarm6_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    write_op_modes:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6